[workspace]
members = [
    "rust",
    "elixir", 
    "typescript"
]

resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["Katalyst Team <team@katalyst.dev>"]
license = "MIT"
repository = "https://github.com/katalyst/framework"

[workspace.dependencies]
# WebAssembly core dependencies
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = "0.3"
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
uuid = { version = "1.0", features = ["v4", "wasm-bindgen"] }
regex = "1.0"
once_cell = "1.0"

# Performance and math (for Rust module)
rayon = "1.8"
ndarray = "0.15"
num-traits = "0.2"
rand = "0.8"

# Async support
tokio = { version = "1.0", features = ["rt", "sync", "time"] }
futures = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
debug = true
incremental = true