[package]
name = "katalyst-tauri"
version = "1.0.0"
description = "Katalyst Tauri 2.0 Desktop, Mobile & WebXR Unified Application"
authors = ["SWC Studio <dev@swcstudio.com>"]
edition = "2021"
rust-version = "1.77"
license = "MIT"
repository = "https://github.com/swcstudio/katalyst"

[build-dependencies]
tauri-build = { workspace = true, features = ["codegen", "isolation"] }

[dependencies]
# Tauri Core
tauri = { workspace = true, features = [
  "api-all",
  "icon-ico",
  "icon-png",
  "system-tray",
  "updater",
  "window-maximize",
  "window-minimize",
  "window-close",
  "window-hide",
  "window-show",
  "window-start-dragging",
  "window-unmaximize",
  "window-unminimize",
  "protocol-asset",
  "shell-open",
  "devtools"
] }

# WebXR Integration 
tauri-plugin-webview = "2.0"
tauri-plugin-window-state = "2.0"

# Mobile Platform Support
tauri-plugin-haptics = "2.0"
tauri-plugin-biometric = "2.0"
tauri-plugin-camera = "2.0"
tauri-plugin-geolocation = "2.0"
tauri-plugin-notification = "2.0"

# Desktop Features
tauri-plugin-global-shortcut = "2.0"
tauri-plugin-clipboard-manager = "2.0"
tauri-plugin-fs = "2.0"
tauri-plugin-dialog = "2.0"
tauri-plugin-shell = "2.0"
tauri-plugin-sql = "2.0"
tauri-plugin-store = "2.0"

# Async Runtime
tokio = { workspace = true }
futures = "0.3"

# Serialization
serde = { workspace = true }
serde_json = "1.0"

# Error Handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Web Server (for WebXR)
warp = "0.3"
tower = "0.4"
tower-http = { version = "0.4", features = ["cors", "fs"] }

# WebXR & 3D
nalgebra = "0.32"
glam = "0.24"

# WebAssembly
wasmtime = "16.0"
wasmtime-wasi = "16.0"

# Multithreading
crossbeam = { workspace = true }
rayon = { workspace = true }

# Window Management
window-vibrancy = "0.4"

# System Integration
dirs = "5.0"
opener = "0.6"

# File Watching
notify = "6.0"

# HTTP Client
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Database
rusqlite = { version = "0.30", features = ["bundled"] }

# Image Processing
image = "0.24"

# Encryption
ring = "0.17"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
devtools = ["tauri/devtools"]
mobile = []
webxr = []

# Mobile targets
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
tauri-plugin-deep-link = "0.1"
tauri-plugin-statusbar = "0.1"

# Build optimizations
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true