[package]
name = "swcstudio-multithreading"
version = "1.0.0"
edition = "2021"
description = "Advanced multithreading system for React 19 with AI-focused thread lifecycle management"
license = "MIT"
repository = "https://github.com/swcstudio/multithreading"
keywords = ["multithreading", "react", "ai", "websocket", "concurrency"]
categories = ["concurrency", "web-programming"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# napi-rs for Node.js bindings
napi = { version = "3.1", default-features = false, features = ["napi4", "async", "tokio_rt"] }
napi-derive = "3.1"

# Core concurrency libraries
crossbeam = "0.8"
rayon = "1.8"
tokio = { version = "1.35", features = ["full"] }

# Advanced synchronization primitives
parking_lot = "0.12"
dashmap = "5.5"
flume = "0.11"
arc-swap = "1.7"
once_cell = "1.19"

# Alternative async runtimes
async-std = { version = "1.12", features = ["attributes"] }
smol = "2.0"
futures = "0.3"
async-trait = "0.1"

# Actor system and OTP patterns
async-channel = "2.1"  # For bounded/unbounded channels
uuid = { version = "1.6", features = ["v4", "fast-rng"] }  # For actor IDs
petgraph = "0.6"  # For supervisor trees
pin-project = "1.1"  # For pinning futures

# Phoenix/Elixir-inspired features
sled = "0.34"  # Embedded database for ETS-like tables
bincode = "1.3"  # Binary serialization
rmp-serde = "1.1"  # MessagePack for efficient message passing

# SIMD and vectorization
wide = "0.7"  # Portable SIMD operations
nalgebra = "0.32"  # Linear algebra

# Memory management
mimalloc = { version = "0.1", default-features = false, optional = true }
bumpalo = "3.15"  # Bump allocator

# Thread-local storage
thread_local = "1.1"

# Concurrent data structures
concurrent-queue = "2.4"
crossbeam-skiplist = "0.1"
evmap = "10.0"

# Profiling and debugging
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-opentelemetry = "0.22"  # For distributed tracing
opentelemetry = "0.21"
metrics = "0.21"  # For telemetry
pprof = { version = "0.13", features = ["flamegraph"], optional = true }

# Additional utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num_cpus = "1.16"
ahash = "0.8"  # Faster hasher
memmap2 = "0.9"  # Memory-mapped files
bytemuck = "1.14"  # Safe transmutation
lazy_static = "1.4"  # For global thread registry
thiserror = "1.0"  # Error handling
anyhow = "1.0"  # Error context
ordered-float = "4.2"  # For ETS float ordering

[features]
default = ["mimalloc"]
profiling = ["pprof"]

[dev-dependencies]
rstest = "0.18"
tokio-test = "0.4"

[build-dependencies]
napi-build = "2.2"
